USE WORKPLACE1;

SELECT E.Fname AS ManagerFirstName, E.Lname AS ManagerLastName FROM DEPARTMENT D JOIN EMPLOYEE E ON D.Mgr_ssn = E.Ssn
WHERE D.Dnumber = (SELECT Dno FROM EMPLOYEE GROUP BY Dno ORDER BY COUNT(*) DESC LIMIT 1);